import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import ProductCard from '../components/ProductCard';
import Section from '../components/Section';
import SectionHeader from '../components/SectionHeader';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mb-5">
        <Header />
        <div className="flex justify-center py-5 divide-x-2 divide-gray-500">
          <h3 className="text-3xl px-10">Top Deals</h3>
          <h3 className="text-3xl px-10">Product Videos</h3>
          <h3 className="text-3xl px-10">Trending</h3>
        </div>

        <section className="w-11/12 mx-auto py-10">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
            <div className="h-56 overflow-hidden relative bg-teal-500 rounded-2xl shadow-lg">
              <Image
                src={'/images/iphone-1.jpg'}
                fill={true}
                objectFit="cover"
              />
            </div>
            <div className="h-56 overflow-hidden relative bg-teal-500 rounded-2xl shadow-lg">
              <Image
                src={'/images/iphone-2.jpg'}
                fill={true}
                objectFit="cover"
              />
            </div>
          </div>
        </section>

        <section className="w-11/12 mx-auto mb-10">
          <SectionHeader label={"Today's Best Deal"} />
          <div className="mt-5 flex justify-evenly flex-wrap">
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
          </div>
        </section>

        <section className="min-h-screen py-10 bg-gray-200">
          <div className="w-11/12 mx-auto space-y-10">
            <div className="h-60 rounded-lg relative overflow-hidden">
              <Image
                src={'/images/banner-1.jpg'}
                fill={true}
                objectFit="cover"
              />
            </div>
            <div className="h-96 bg-teal-500 rounded-lg"></div>
          </div>
        </section>

        <Section label={'Top Deals'}>
          <div className="flex gap-5">
            <div className="h-40 w-40 bg-gray-400 rounded-lg"></div>
            <div className="h-40 w-40 bg-gray-400 rounded-lg"></div>
            <div className="h-40 w-40 bg-gray-400 rounded-lg"></div>
            <div className="h-40 w-40 bg-gray-400 rounded-lg"></div>
            <div className="h-40 w-40 bg-gray-400 rounded-lg"></div>
            <div className="h-40 w-40 bg-gray-400 rounded-lg"></div>
            <div className="h-40 w-40 bg-gray-400 rounded-lg"></div>
            <div className="h-40 w-40 bg-gray-400 rounded-lg"></div>
          </div>
        </Section>
      </main>
    </div>
  );
}
