import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'h-screen flex justify-center items-center'}>
        <h1>MiMall</h1>
      </main>
    </div>
  );
}
